name: Cypress Tests

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          browser: firefox
          headless: true
